using System.Text.Json.Serialization;
using NeoAstra.Rpc;

[assembly: NeoRpcJsonContext(typeof(CodeAlta.Desktop.Rpc.DesktopJsonContext))]

namespace CodeAlta.Desktop.Rpc;

[NeoRpcService("boot", Version = 1)]
internal sealed class BootService
{
    private readonly string? _epoch;
    private readonly bool _commandReview;
    private readonly bool _userInput;
    private readonly bool _developer;
    internal BootService() { }
    internal BootService(string epoch) { _epoch = epoch; }
    internal BootService(string epoch, bool commandReview) { _epoch = epoch; _commandReview = commandReview; }
    internal BootService(string epoch, bool commandReview, bool userInput) : this(epoch, commandReview) { _userInput = userInput; }
    internal BootService(string epoch, bool commandReview, bool userInput, bool developer) : this(epoch, commandReview, userInput) { _developer = developer; }
    /// <summary>
    /// Receives the theme the window shows, so the next start can paint the window in its background before
    /// any page exists. Null when this host keeps no appearance.
    /// </summary>
    internal Action<DesktopAppearance>? RememberAppearance { get; init; }

    /// <summary>
    /// True while the window repairs a configuration file that cannot be loaded: there is no host yet, and the
    /// page shows the <c>startupConfig</c> editor instead of the workspace.
    /// </summary>
    internal bool ConfigRecovery { get; init; }

    /// <summary>True when the application started without any enabled model provider.</summary>
    internal bool ProviderSetup { get; init; }

    /// <summary>True for the developer instance, for a window that has no host.</summary>
    internal bool Developer { get; init; }

    /// <summary>Remembers the window's theme and background for the next start.</summary>
    [NeoRpcMethod("appearance")]
    public BootAppearanceResponse Appearance(BootAppearanceRequest request)
    {
        if (!DesktopAppearance.TryCreate(request?.Theme, request?.Background, out var appearance)) return new("invalid_request");
        if (RememberAppearance is null) return new("unavailable");
        RememberAppearance(appearance);
        return new("ok");
    }

    [NeoRpcMethod("status")]
    public BootStatus Status(BootRequest request) => ConfigRecovery
        ? new("config-recovery", "CodeAlta", DesktopCommandLine.Version, false) { ConfigRecovery = true, DeveloperMode = Developer || _developer }
        : _epoch is null
        ? new("in-development", "CodeAlta", DesktopCommandLine.Version, false)
        : new("owned-text-only", "CodeAlta", DesktopCommandLine.Version, true) { HostEpoch = _epoch, CommandReviewEnabled = _commandReview, OwnedAsksEnabled = true, OwnedUserInputEnabled = _userInput, DeveloperMode = Developer || _developer, ProviderSetup = ProviderSetup };
}

internal sealed record BootRequest;

/// <summary>The window's theme (<c>dark</c> or <c>light</c>) and its background as <c>#rrggbb</c>.</summary>
internal sealed record BootAppearanceRequest(string? Theme, string? Background);

/// <summary><c>ok</c>, <c>invalid_request</c>, or <c>unavailable</c> when the host keeps no appearance.</summary>
internal sealed record BootAppearanceResponse(string Status);
internal sealed record BootStatus(string State, string ProductName, string Version, bool HostAvailable)
{
    public string? HostEpoch { get; init; }
    public bool CommandReviewEnabled { get; init; }
    public bool OwnedAsksEnabled { get; init; }
    public bool OwnedUserInputEnabled { get; init; }

    /// <summary>True for the developer instance, which runs beside the normal one with its own sessions.</summary>
    public bool DeveloperMode { get; init; }

    /// <summary>True while the configuration file is being repaired; the page then shows only its editor.</summary>
    public bool ConfigRecovery { get; init; }

    /// <summary>
    /// True when the application started without any enabled model provider (a first start, usually): the
    /// page opens the provider settings and guides through them, as the terminal application opens its own.
    /// </summary>
    public bool ProviderSetup { get; init; }
}

[JsonSerializable(typeof(BootRequest))]
[JsonSerializable(typeof(BootAppearanceRequest))]
[JsonSerializable(typeof(BootAppearanceResponse))]
[JsonSerializable(typeof(AppUpdateRequest))]
[JsonSerializable(typeof(AppUpdateCheckRequest))]
[JsonSerializable(typeof(AppUpdateResponse))]
[JsonSerializable(typeof(AppUpdateOpenResponse))]
[JsonSerializable(typeof(DesktopShellRequest))]
[JsonSerializable(typeof(DesktopShellOnCloseRequest))]
[JsonSerializable(typeof(DesktopShellSessionWidthRequest))]
[JsonSerializable(typeof(DesktopShellReviewPermissionsRequest))]
[JsonSerializable(typeof(DesktopShellZoomRequest))]
[JsonSerializable(typeof(DesktopShellHideResponse))]
[JsonSerializable(typeof(DesktopShellExitRequest))]
[JsonSerializable(typeof(DesktopShellExitResponse))]
[JsonSerializable(typeof(DesktopShellRevealEntryResponse))]
[JsonSerializable(typeof(DesktopShellPickFolderRequest))]
[JsonSerializable(typeof(DesktopShellPickFolderResponse))]
[JsonSerializable(typeof(DesktopShellPreferences))]
[JsonSerializable(typeof(DesktopShellEvent))]
[JsonSerializable(typeof(ColorSchemesRequest))]
[JsonSerializable(typeof(ColorSchemesListResponse))]
[JsonSerializable(typeof(ColorSchemeSaveRequest))]
[JsonSerializable(typeof(ColorSchemeSaveResponse))]
[JsonSerializable(typeof(ColorSchemeIdRequest))]
[JsonSerializable(typeof(ColorSchemeChangeResponse))]
[JsonSerializable(typeof(StartupConfigRequest))]
[JsonSerializable(typeof(StartupConfigContentRequest))]
[JsonSerializable(typeof(StartupConfigDocument))]
[JsonSerializable(typeof(StartupConfigValidation))]
[JsonSerializable(typeof(StartupConfigSaveResponse))]
[JsonSerializable(typeof(StartupConfigExitResponse))]
[JsonSerializable(typeof(ApplicationLogsRequest))]
[JsonSerializable(typeof(ApplicationLogsResponse))]
[JsonSerializable(typeof(ApplicationLogsClearRequest))]
[JsonSerializable(typeof(ApplicationLogsClearResponse))]
[JsonSerializable(typeof(SessionChoicesRequest))]
[JsonSerializable(typeof(SessionChoicesResponse))]
[JsonSerializable(typeof(SessionProviderChoices))]
[JsonSerializable(typeof(SessionProviderRequest))]
[JsonSerializable(typeof(SessionProviderResult))]
[JsonSerializable(typeof(SessionStopBackgroundTaskRequest))]
[JsonSerializable(typeof(SessionStopBackgroundTaskResult))]
[JsonSerializable(typeof(SessionRuntimeBackgroundTaskResponse))]
[JsonSerializable(typeof(BootStatus))]
[JsonSerializable(typeof(WorkspaceRequest))]
[JsonSerializable(typeof(WorkspaceSnapshot))]
[JsonSerializable(typeof(WorkspaceOpenProjectRequest))]
[JsonSerializable(typeof(WorkspaceArchiveProjectRequest))]
[JsonSerializable(typeof(WorkspaceArchiveProjectResponse))]
[JsonSerializable(typeof(WorkspaceOpenProjectResponse))]
[JsonSerializable(typeof(WorkspaceDirectoryCompletionRequest))]
[JsonSerializable(typeof(WorkspaceDirectoryCompletionResponse))]
[JsonSerializable(typeof(WorkspaceReadProjectNameRequest))]
[JsonSerializable(typeof(WorkspaceReadProjectNameResponse))]
[JsonSerializable(typeof(WorkspaceRenameProjectRequest))]
[JsonSerializable(typeof(WorkspaceRenameProjectResponse))]
[JsonSerializable(typeof(WorkspaceCreateSessionRequest))]
[JsonSerializable(typeof(WorkspaceCreateSessionResponse))]
[JsonSerializable(typeof(WorkspaceDraftPromptsRequest))]
[JsonSerializable(typeof(WorkspaceDraftPromptsResponse))]
[JsonSerializable(typeof(WorkspaceRenameSessionRequest))]
[JsonSerializable(typeof(WorkspaceRenameSessionResponse))]
[JsonSerializable(typeof(WorkspaceDeleteSessionRequest))]
[JsonSerializable(typeof(WorkspaceDeleteSessionResponse))]
[JsonSerializable(typeof(WorkspaceProject))]
[JsonSerializable(typeof(WorkspaceSession))]
[JsonSerializable(typeof(ConfigurationRequest))]
[JsonSerializable(typeof(ConfigurationSnapshot))]
[JsonSerializable(typeof(ConfigurationProvider))]
[JsonSerializable(typeof(ConfigurationProviderBrand))]
[JsonSerializable(typeof(ConfigurationPlugin))]
[JsonSerializable(typeof(GlobalConfigReadRequest))]
[JsonSerializable(typeof(GlobalConfigReadResponse))]
[JsonSerializable(typeof(GlobalConfigValidateRequest))]
[JsonSerializable(typeof(GlobalConfigValidationResponse))]
[JsonSerializable(typeof(GlobalConfigSaveRequest))]
[JsonSerializable(typeof(GlobalConfigSaveResponse))]
[JsonSerializable(typeof(GlobalConfigProvidersRequest))]
[JsonSerializable(typeof(GlobalConfigProvidersResponse))]
[JsonSerializable(typeof(GlobalConfigProvider))]
[JsonSerializable(typeof(GlobalConfigUnsupportedProvider))]
[JsonSerializable(typeof(GlobalConfigProviderDefaults))]
[JsonSerializable(typeof(GlobalConfigProviderTypeDefaults))]
[JsonSerializable(typeof(GlobalConfigBuiltInProvider))]
[JsonSerializable(typeof(GlobalConfigAddBuiltInProviderRequest))]
[JsonSerializable(typeof(GlobalConfigProviderEdit))]
[JsonSerializable(typeof(GlobalConfigSaveProviderRequest))]
[JsonSerializable(typeof(GlobalConfigDeleteProviderRequest))]
[JsonSerializable(typeof(ProviderUsageRequest))]
[JsonSerializable(typeof(ProviderUsageResponse))]
[JsonSerializable(typeof(ProviderLoginStatusRequest))]
[JsonSerializable(typeof(ProviderLoginStatusResponse))]
[JsonSerializable(typeof(ProviderLoginRequest))]
[JsonSerializable(typeof(ProviderLoginEvent))]
[JsonSerializable(typeof(ProviderLogoutResponse))]
[JsonSerializable(typeof(McpServersListRequest))]
[JsonSerializable(typeof(McpServersListResponse))]
[JsonSerializable(typeof(McpServerEntry))]
[JsonSerializable(typeof(McpUnsupportedServer))]
[JsonSerializable(typeof(McpServerValueName))]
[JsonSerializable(typeof(McpServerValueEdit))]
[JsonSerializable(typeof(McpServerEdit))]
[JsonSerializable(typeof(McpServersSaveRequest))]
[JsonSerializable(typeof(McpServersRemoveRequest))]
[JsonSerializable(typeof(McpServersSetEnabledRequest))]
[JsonSerializable(typeof(McpServersMutationResponse))]
[JsonSerializable(typeof(McpServerLoginRequest))]
[JsonSerializable(typeof(McpServerLoginEvent))]
[JsonSerializable(typeof(McpServerLogoutResponse))]
[JsonSerializable(typeof(AgentPromptsListRequest))]
[JsonSerializable(typeof(AgentPromptsListResponse))]
[JsonSerializable(typeof(AgentPromptEntry))]
[JsonSerializable(typeof(AgentPromptReadRequest))]
[JsonSerializable(typeof(AgentPromptReadResponse))]
[JsonSerializable(typeof(AgentPromptDocument))]
[JsonSerializable(typeof(AgentPromptSaveRequest))]
[JsonSerializable(typeof(AgentPromptDeleteRequest))]
[JsonSerializable(typeof(AgentPromptMutationResponse))]
[JsonSerializable(typeof(SkillsListRequest))]
[JsonSerializable(typeof(SkillsDetailRequest))]
[JsonSerializable(typeof(SkillsDetailResponse))]
[JsonSerializable(typeof(SkillsListResponse))]
[JsonSerializable(typeof(SkillsEntry))]
[JsonSerializable(typeof(SkillsSetEnabledRequest))]
[JsonSerializable(typeof(SkillsSetAllEnabledRequest))]
[JsonSerializable(typeof(SkillsMutationResponse))]
[JsonSerializable(typeof(SkillsCreateRequest))]
[JsonSerializable(typeof(SkillsCreateResponse))]
[JsonSerializable(typeof(SettingsFilesListRequest))]
[JsonSerializable(typeof(SettingsFilesListResponse))]
[JsonSerializable(typeof(SettingsFileLocation))]
[JsonSerializable(typeof(SettingsFileRequest))]
[JsonSerializable(typeof(SettingsFileResponse))]
[JsonSerializable(typeof(PluginsListRequest))]
[JsonSerializable(typeof(PluginsListResponse))]
[JsonSerializable(typeof(PluginsEntry))]
[JsonSerializable(typeof(PluginsSetEnabledRequest))]
[JsonSerializable(typeof(PluginsMutationResponse))]
[JsonSerializable(typeof(PluginsPackageRequest))]
[JsonSerializable(typeof(PluginsCreateRequest))]
[JsonSerializable(typeof(PluginsCreateResponse))]
[JsonSerializable(typeof(ModelCatalogProvidersRequest))]
[JsonSerializable(typeof(ModelCatalogProvidersResponse))]
[JsonSerializable(typeof(ModelCatalogProvider))]
[JsonSerializable(typeof(ModelCatalogProbeRequest))]
[JsonSerializable(typeof(ModelCatalogProbeResponse))]
[JsonSerializable(typeof(ModelCatalogModelsRequest))]
[JsonSerializable(typeof(ModelCatalogModelsResponse))]
[JsonSerializable(typeof(ModelCatalogModel))]
[JsonSerializable(typeof(ReminderListRequest))]
[JsonSerializable(typeof(ReminderActiveRequest))]
[JsonSerializable(typeof(ReminderActiveResponse))]
[JsonSerializable(typeof(ReminderDetailRequest))]
[JsonSerializable(typeof(ReminderDetailResponse))]
[JsonSerializable(typeof(ReminderCreateRequest))]
[JsonSerializable(typeof(ReminderSaveRequest))]
[JsonSerializable(typeof(ReminderDeleteRequest))]
[JsonSerializable(typeof(ReminderMutationResponse))]
[JsonSerializable(typeof(ReminderListResponse))]
[JsonSerializable(typeof(ReminderRow))]
[JsonSerializable(typeof(GitIssuesSearchRequest))]
[JsonSerializable(typeof(GitIssuesSearchResponse))]
[JsonSerializable(typeof(GitIssueEntry))]
[JsonSerializable(typeof(IssueSourcesRequest))]
[JsonSerializable(typeof(IssueSourcesResponse))]
[JsonSerializable(typeof(IssueSource))]
[JsonSerializable(typeof(IssueListRequest))]
[JsonSerializable(typeof(IssueListResponse))]
[JsonSerializable(typeof(IssueRow))]
[JsonSerializable(typeof(IssueLabel))]
[JsonSerializable(typeof(IssueItemRequest))]
[JsonSerializable(typeof(IssueReadResponse))]
[JsonSerializable(typeof(IssueComment))]
[JsonSerializable(typeof(IssueStartRequest))]
[JsonSerializable(typeof(IssueStartResponse))]
[JsonSerializable(typeof(IssueLinkRequest))]
[JsonSerializable(typeof(IssueLinkResponse))]
[JsonSerializable(typeof(MarkdownLinkRequest))]
[JsonSerializable(typeof(MarkdownLinkResponse))]
[JsonSerializable(typeof(PullRequestPromptsRequest))]
[JsonSerializable(typeof(PullRequestPromptsResponse))]
[JsonSerializable(typeof(PullRequestPromptItem))]
[JsonSerializable(typeof(PullRequestPromptSaveRequest))]
[JsonSerializable(typeof(PullRequestPromptSaveResponse))]
[JsonSerializable(typeof(PullRequestPromptDeleteRequest))]
[JsonSerializable(typeof(SpacesRequest))]
[JsonSerializable(typeof(SpacesResponse))]
[JsonSerializable(typeof(SpaceItem))]
[JsonSerializable(typeof(SpaceCreateRequest))]
[JsonSerializable(typeof(SpaceUpdateRequest))]
[JsonSerializable(typeof(SpaceDeleteRequest))]
[JsonSerializable(typeof(SpaceAssignRequest))]
[JsonSerializable(typeof(SpaceReorderRequest))]
[JsonSerializable(typeof(SpaceShownRequest))]
[JsonSerializable(typeof(SpaceChangeResponse))]
[JsonSerializable(typeof(SpacesEvent))]
[JsonSerializable(typeof(SpacesActivityResponse))]
[JsonSerializable(typeof(SpaceSessionActivity))]
[JsonSerializable(typeof(HistoryRequest))]
[JsonSerializable(typeof(HistoryResponse))]
[JsonSerializable(typeof(HistoryImage))]
[JsonSerializable(typeof(TimelineHistoryResponse))]
[JsonSerializable(typeof(HistorySourceResponse))]
[JsonSerializable(typeof(HistorySourceRequest))]
[JsonSerializable(typeof(SessionSendRequest))]
[JsonSerializable(typeof(SessionReferenceSearchRequest))]
[JsonSerializable(typeof(SessionReferenceSearchResponse))]
[JsonSerializable(typeof(SessionReferenceObservationRequest))]
[JsonSerializable(typeof(SessionReferenceObservationResponse))]
[JsonSerializable(typeof(SessionAbortRequest))]
[JsonSerializable(typeof(SessionSteerRequest))]
[JsonSerializable(typeof(SessionCompactRequest))]
[JsonSerializable(typeof(SessionAbortRunRequest))]
[JsonSerializable(typeof(SessionQueueRequest))]
[JsonSerializable(typeof(SessionCancelQueueRequest))]
[JsonSerializable(typeof(SessionQueueInsertionView))]
[JsonSerializable(typeof(SessionReceiptRequest))]
[JsonSerializable(typeof(SessionAdmission))]
[JsonSerializable(typeof(SessionReceiptPage))]
[JsonSerializable(typeof(SessionDisplayRequest))]
[JsonSerializable(typeof(SessionDisplayItem))]
[JsonSerializable(typeof(SessionRuntimeStateRequest))]
[JsonSerializable(typeof(SessionRuntimeScopedRequest))]
[JsonSerializable(typeof(SessionRuntimeScopedResponse))]
[JsonSerializable(typeof(SessionRuntimeStateResponse))]
[JsonSerializable(typeof(SessionUsageRequest))]
[JsonSerializable(typeof(SessionUsageResponse))]
[JsonSerializable(typeof(SessionPermissionsRequest))]
[JsonSerializable(typeof(SessionPermissionsPage))]
[JsonSerializable(typeof(SessionPermissionResolveRequest))]
[JsonSerializable(typeof(SessionPermissionResolution))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(SessionAsksRequest))]
[JsonSerializable(typeof(SessionAsksPage))]
[JsonSerializable(typeof(SessionAskActionRequest))]
[JsonSerializable(typeof(SessionAskObservationRequest))]
[JsonSerializable(typeof(SessionAskResult))]
[JsonSerializable(typeof(SessionNotesRequest))]
[JsonSerializable(typeof(SessionNotesResponse))]
[JsonSerializable(typeof(SessionNotesClearResponse))]
[JsonSerializable(typeof(SessionPluginEventsRequest))]
[JsonSerializable(typeof(SessionPluginEventsResponse))]
[JsonSerializable(typeof(ProjectFileReadRequest))]
[JsonSerializable(typeof(ProjectFileReadResponse))]
[JsonSerializable(typeof(ProjectFileWriteRequest))]
[JsonSerializable(typeof(ProjectFileWriteResponse))]
[JsonSerializable(typeof(ProjectFileListRequest))]
[JsonSerializable(typeof(ProjectFileListResponse))]
[JsonSerializable(typeof(ProjectFileStatRequest))]
[JsonSerializable(typeof(ProjectFileStatResponse))]
[JsonSerializable(typeof(ProjectFileCreateRequest))]
[JsonSerializable(typeof(ProjectFileRenameRequest))]
[JsonSerializable(typeof(ProjectFileDeleteRequest))]
[JsonSerializable(typeof(ProjectFileChangeResponse))]
[JsonSerializable(typeof(ProjectFileImageRequest))]
[JsonSerializable(typeof(ProjectFileImageResponse))]
[JsonSerializable(typeof(ProjectFileRevealRequest))]
[JsonSerializable(typeof(ProjectFileSearchRequest))]
[JsonSerializable(typeof(ProjectFileSearchEvent))]
[JsonSerializable(typeof(ProjectFileWatchRequest))]
[JsonSerializable(typeof(ProjectFileShowEvent))]
[JsonSerializable(typeof(ProjectGitStatusRequest))]
[JsonSerializable(typeof(ProjectGitStatusResponse))]
[JsonSerializable(typeof(ProjectGitChangesRequest))]
[JsonSerializable(typeof(ProjectGitChangesResponse))]
[JsonSerializable(typeof(ProjectGitCommitsRequest))]
[JsonSerializable(typeof(ProjectGitCommitsResponse))]
[JsonSerializable(typeof(ProjectGitFileRequest))]
[JsonSerializable(typeof(ProjectGitFileResponse))]
[JsonSerializable(typeof(ProjectGitWatchRequest))]
[JsonSerializable(typeof(ProjectGitShowEvent))]
[JsonSerializable(typeof(PromptImageRequest))]
[JsonSerializable(typeof(PromptImageResponse))]
[JsonSerializable(typeof(ComposerStatusRequest))]
[JsonSerializable(typeof(ComposerStatusResponse))]
[JsonSerializable(typeof(UserInputListRequest))]
[JsonSerializable(typeof(UserInputPage))]
[JsonSerializable(typeof(UserInputResolveRequest))]
[JsonSerializable(typeof(UserInputCancelRequest))]
[JsonSerializable(typeof(UserInputResult))]
[JsonSerializable(typeof(PluginUiScopeRequest))]
[JsonSerializable(typeof(PluginUiContributionsResponse))]
[JsonSerializable(typeof(PluginUiRegionsResponse))]
[JsonSerializable(typeof(PluginUiInvokeRequest))]
[JsonSerializable(typeof(PluginUiStatusResponse))]
[JsonSerializable(typeof(PluginUiPickerRequest))]
[JsonSerializable(typeof(PluginUiPickerResponse))]
[JsonSerializable(typeof(PluginUiWatchRequest))]
[JsonSerializable(typeof(PluginUiEvent))]
[JsonSerializable(typeof(PluginUiAnswer))]
[JsonSerializable(typeof(PluginUiActionRequest))]
[JsonSerializable(typeof(PluginUiActionResponse))]
[JsonSerializable(typeof(TerminalsRequest))]
[JsonSerializable(typeof(TerminalProfilesResponse))]
[JsonSerializable(typeof(TerminalCreateRequest))]
[JsonSerializable(typeof(TerminalCreateResponse))]
[JsonSerializable(typeof(TerminalInputRequest))]
[JsonSerializable(typeof(TerminalResizeRequest))]
[JsonSerializable(typeof(TerminalRenameRequest))]
[JsonSerializable(typeof(TerminalIdRequest))]
[JsonSerializable(typeof(TerminalLinkRequest))]
[JsonSerializable(typeof(TerminalViewRequest))]
[JsonSerializable(typeof(TerminalShowRequest))]
[JsonSerializable(typeof(TerminalAcknowledgeRequest))]
[JsonSerializable(typeof(TerminalReply))]
[JsonSerializable(typeof(TerminalEvent))]
[JsonSerializable(typeof(WorktreesRequest))]
[JsonSerializable(typeof(WorktreesListResponse))]
[JsonSerializable(typeof(WorktreeRemoveRequest))]
[JsonSerializable(typeof(WorktreeChangeResponse))]
[JsonSerializable(typeof(WorktreeBranchesRequest))]
[JsonSerializable(typeof(WorktreeBranchesResponse))]
[JsonSerializable(typeof(WorktreeSwitchRequest))]
[JsonSerializable(typeof(WorktreeSettingsRequest))]
[JsonSerializable(typeof(WorktreeSettingsSaveRequest))]
[JsonSerializable(typeof(WorktreeSettingsResponse))]
[JsonSerializable(typeof(ToolCallRequest))]
[JsonSerializable(typeof(ToolCallResponse))]
[JsonSerializable(typeof(ToolCallObserveRequest))]
[JsonSerializable(typeof(ToolCallOutputItem))]
[JsonSerializable(typeof(McpHostRequest))]
[JsonSerializable(typeof(McpHostEnableRequest))]
[JsonSerializable(typeof(McpHostResponse))]
[JsonSerializable(typeof(AutomationsRequest))]
[JsonSerializable(typeof(AutomationsListResponse))]
[JsonSerializable(typeof(AutomationSaveRequest))]
[JsonSerializable(typeof(AutomationIdRequest))]
[JsonSerializable(typeof(AutomationEnableRequest))]
[JsonSerializable(typeof(AutomationPauseRequest))]
[JsonSerializable(typeof(AutomationRunsRequest))]
[JsonSerializable(typeof(AutomationPreviewRequest))]
[JsonSerializable(typeof(AutomationMutationResponse))]
[JsonSerializable(typeof(AutomationRunResponse))]
[JsonSerializable(typeof(AutomationRunsResponse))]
[JsonSerializable(typeof(AutomationPreviewResponse))]
[JsonSerializable(typeof(AutomationsEvent))]
[JsonSerializable(typeof(WorkItemsRequest))]
[JsonSerializable(typeof(WorkItemsListResponse))]
[JsonSerializable(typeof(WorkItemRequest))]
[JsonSerializable(typeof(WorkItemReadResponse))]
[JsonSerializable(typeof(WorkItemActionRequest))]
[JsonSerializable(typeof(WorkItemActionResponse))]
[JsonSerializable(typeof(WorkItemsSettingsRequest))]
[JsonSerializable(typeof(WorkItemsSettingsResponse))]
[JsonSerializable(typeof(WorkItemsEvent))]
internal sealed partial class DesktopJsonContext : JsonSerializerContext;
