using System.Text.Json.Serialization;
using NeoAstra.Rpc;

[assembly: NeoRpcJsonContext(typeof(CodeAlta.Desktop.Rpc.DesktopJsonContext))]

namespace CodeAlta.Desktop.Rpc;

[NeoRpcService("boot", Version = 1)]
internal sealed class BootService
{
    private readonly string? _epoch;
    private readonly bool _commandReview;
    private readonly bool _userInput;
    internal BootService() { }
    internal BootService(string epoch) { _epoch = epoch; }
    internal BootService(string epoch, bool commandReview) { _epoch = epoch; _commandReview = commandReview; }
    internal BootService(string epoch, bool commandReview, bool userInput) : this(epoch, commandReview) { _userInput = userInput; }
    [NeoRpcMethod("status")]
    public BootStatus Status(BootRequest request) => _epoch is null
        ? new("in-development", "CodeAlta", DesktopCommandLine.Version, false)
        : new("owned-text-only", "CodeAlta", DesktopCommandLine.Version, true) { HostEpoch = _epoch, CommandReviewEnabled = _commandReview, OwnedAsksEnabled = true, OwnedUserInputEnabled = _userInput };
}

internal sealed record BootRequest;
internal sealed record BootStatus(string State, string ProductName, string Version, bool HostAvailable)
{
    public string? HostEpoch { get; init; }
    public bool CommandReviewEnabled { get; init; }
    public bool OwnedAsksEnabled { get; init; }
    public bool OwnedUserInputEnabled { get; init; }
}

[JsonSerializable(typeof(BootRequest))]
[JsonSerializable(typeof(ApplicationLogsRequest))]
[JsonSerializable(typeof(ApplicationLogsResponse))]
[JsonSerializable(typeof(ApplicationLogsClearRequest))]
[JsonSerializable(typeof(ApplicationLogsClearResponse))]
[JsonSerializable(typeof(SessionChoicesRequest))]
[JsonSerializable(typeof(SessionChoicesResponse))]
[JsonSerializable(typeof(SessionProviderChoices))]
[JsonSerializable(typeof(SessionProviderRequest))]
[JsonSerializable(typeof(SessionProviderResult))]
[JsonSerializable(typeof(BootStatus))]
[JsonSerializable(typeof(WorkspaceRequest))]
[JsonSerializable(typeof(WorkspaceSnapshot))]
[JsonSerializable(typeof(WorkspaceOpenProjectRequest))]
[JsonSerializable(typeof(WorkspaceArchiveProjectRequest))]
[JsonSerializable(typeof(WorkspaceArchiveProjectResponse))]
[JsonSerializable(typeof(WorkspaceOpenProjectResponse))]
[JsonSerializable(typeof(WorkspaceDirectoryCompletionRequest))]
[JsonSerializable(typeof(WorkspaceDirectoryCompletionResponse))]
[JsonSerializable(typeof(WorkspaceReadProjectNameRequest))]
[JsonSerializable(typeof(WorkspaceReadProjectNameResponse))]
[JsonSerializable(typeof(WorkspaceRenameProjectRequest))]
[JsonSerializable(typeof(WorkspaceRenameProjectResponse))]
[JsonSerializable(typeof(WorkspaceCreateSessionRequest))]
[JsonSerializable(typeof(WorkspaceCreateSessionResponse))]
[JsonSerializable(typeof(WorkspaceDraftPromptsRequest))]
[JsonSerializable(typeof(WorkspaceDraftPromptsResponse))]
[JsonSerializable(typeof(WorkspaceRenameSessionRequest))]
[JsonSerializable(typeof(WorkspaceRenameSessionResponse))]
[JsonSerializable(typeof(WorkspaceDeleteSessionRequest))]
[JsonSerializable(typeof(WorkspaceDeleteSessionResponse))]
[JsonSerializable(typeof(WorkspaceProject))]
[JsonSerializable(typeof(WorkspaceSession))]
[JsonSerializable(typeof(ConfigurationRequest))]
[JsonSerializable(typeof(ConfigurationSnapshot))]
[JsonSerializable(typeof(ConfigurationProvider))]
[JsonSerializable(typeof(ConfigurationPlugin))]
[JsonSerializable(typeof(GlobalConfigReadRequest))]
[JsonSerializable(typeof(GlobalConfigReadResponse))]
[JsonSerializable(typeof(GlobalConfigValidateRequest))]
[JsonSerializable(typeof(GlobalConfigValidationResponse))]
[JsonSerializable(typeof(GlobalConfigSaveRequest))]
[JsonSerializable(typeof(GlobalConfigSaveResponse))]
[JsonSerializable(typeof(GlobalConfigProvidersRequest))]
[JsonSerializable(typeof(GlobalConfigProvidersResponse))]
[JsonSerializable(typeof(GlobalConfigProvider))]
[JsonSerializable(typeof(GlobalConfigProviderEdit))]
[JsonSerializable(typeof(GlobalConfigSaveProviderRequest))]
[JsonSerializable(typeof(GlobalConfigDeleteProviderRequest))]
[JsonSerializable(typeof(McpServersListRequest))]
[JsonSerializable(typeof(McpServersListResponse))]
[JsonSerializable(typeof(McpServerEntry))]
[JsonSerializable(typeof(McpServerValueName))]
[JsonSerializable(typeof(McpServerValueEdit))]
[JsonSerializable(typeof(McpServerEdit))]
[JsonSerializable(typeof(McpServersSaveRequest))]
[JsonSerializable(typeof(McpServersRemoveRequest))]
[JsonSerializable(typeof(McpServersSetEnabledRequest))]
[JsonSerializable(typeof(McpServersMutationResponse))]
[JsonSerializable(typeof(ModelCatalogProvidersRequest))]
[JsonSerializable(typeof(ModelCatalogProvidersResponse))]
[JsonSerializable(typeof(ModelCatalogProvider))]
[JsonSerializable(typeof(ModelCatalogProbeRequest))]
[JsonSerializable(typeof(ModelCatalogProbeResponse))]
[JsonSerializable(typeof(ModelCatalogModelsRequest))]
[JsonSerializable(typeof(ModelCatalogModelsResponse))]
[JsonSerializable(typeof(ModelCatalogModel))]
[JsonSerializable(typeof(PromptCatalogRequest))]
[JsonSerializable(typeof(PromptCatalogResponse))]
[JsonSerializable(typeof(McpInventoryResponse))]
[JsonSerializable(typeof(McpInventoryRequest))]
[JsonSerializable(typeof(CodeAlta.Plugin.Mcp.McpInventoryServer))]
[JsonSerializable(typeof(PromptCatalogEntry))]
[JsonSerializable(typeof(ReminderListRequest))]
[JsonSerializable(typeof(ReminderDetailRequest))]
[JsonSerializable(typeof(ReminderDetailResponse))]
[JsonSerializable(typeof(ReminderCreateRequest))]
[JsonSerializable(typeof(ReminderSaveRequest))]
[JsonSerializable(typeof(ReminderDeleteRequest))]
[JsonSerializable(typeof(ReminderMutationResponse))]
[JsonSerializable(typeof(ReminderListResponse))]
[JsonSerializable(typeof(ReminderRow))]
[JsonSerializable(typeof(HistoryRequest))]
[JsonSerializable(typeof(HistoryResponse))]
[JsonSerializable(typeof(TimelineHistoryResponse))]
[JsonSerializable(typeof(HistorySourceResponse))]
[JsonSerializable(typeof(HistorySourceRequest))]
[JsonSerializable(typeof(SessionSendRequest))]
[JsonSerializable(typeof(SessionReferenceSearchRequest))]
[JsonSerializable(typeof(SessionReferenceSearchResponse))]
[JsonSerializable(typeof(SessionReferenceObservationRequest))]
[JsonSerializable(typeof(SessionReferenceObservationResponse))]
[JsonSerializable(typeof(SessionAbortRequest))]
[JsonSerializable(typeof(SessionSteerRequest))]
[JsonSerializable(typeof(SessionCompactRequest))]
[JsonSerializable(typeof(SessionAbortRunRequest))]
[JsonSerializable(typeof(SessionQueueRequest))]
[JsonSerializable(typeof(SessionCancelQueueRequest))]
[JsonSerializable(typeof(SessionQueueInsertionView))]
[JsonSerializable(typeof(SessionReceiptRequest))]
[JsonSerializable(typeof(SessionAdmission))]
[JsonSerializable(typeof(SessionReceiptPage))]
[JsonSerializable(typeof(SessionDisplayRequest))]
[JsonSerializable(typeof(SessionDisplayItem))]
[JsonSerializable(typeof(SessionRuntimeStateRequest))]
[JsonSerializable(typeof(SessionRuntimeScopedRequest))]
[JsonSerializable(typeof(SessionRuntimeScopedResponse))]
[JsonSerializable(typeof(SessionRuntimeStateResponse))]
[JsonSerializable(typeof(SkillsScanRequest))]
[JsonSerializable(typeof(PromptCreateRequest))]
[JsonSerializable(typeof(PromptCreateResponse))]
[JsonSerializable(typeof(SkillsScanResponse))]
[JsonSerializable(typeof(SessionUsageRequest))]
[JsonSerializable(typeof(SessionUsageResponse))]
[JsonSerializable(typeof(SessionPermissionsRequest))]
[JsonSerializable(typeof(SessionPermissionsPage))]
[JsonSerializable(typeof(SessionPermissionResolveRequest))]
[JsonSerializable(typeof(SessionPermissionResolution))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(SessionAsksRequest))]
[JsonSerializable(typeof(SessionAsksPage))]
[JsonSerializable(typeof(SessionAskActionRequest))]
[JsonSerializable(typeof(SessionAskObservationRequest))]
[JsonSerializable(typeof(SessionAskResult))]
[JsonSerializable(typeof(SessionNotesRequest))]
[JsonSerializable(typeof(SessionNotesResponse))]
[JsonSerializable(typeof(SessionNotesClearResponse))]
[JsonSerializable(typeof(UserInputListRequest))]
[JsonSerializable(typeof(UserInputPage))]
[JsonSerializable(typeof(UserInputResolveRequest))]
[JsonSerializable(typeof(UserInputCancelRequest))]
[JsonSerializable(typeof(UserInputResult))]
internal sealed partial class DesktopJsonContext : JsonSerializerContext;
