namespace CodeAlta.Catalog.Worktrees;

public static partial class WorktreeNames
{
    // 275 words.
    private static readonly string[] AdjectiveWords =
    [
        "able", "agile", "airy", "alert", "alpine", "amber", "ample", "ancient", "arctic", "ardent", "astral",
        "autumn", "azure", "balmy", "blithe", "bold", "boreal", "brave", "breezy", "bright", "brilliant", "brisk",
        "bronze", "buoyant", "calm", "candid", "canny", "carefree", "cheery", "chipper", "civil", "classic",
        "clear", "clever", "cobalt", "cool", "copper", "coral", "cosmic", "cozy", "crimson", "crisp", "curious",
        "dapper", "daring", "dashing", "dawning", "dazzling", "deft", "devoted", "dewy", "distant", "dreamy",
        "dusky", "dynamic", "eager", "early", "earnest", "earthy", "easy", "elated", "electric", "elegant",
        "emerald", "epic", "fabled", "fair", "faithful", "fancy", "fearless", "feisty", "festive", "fiery", "fleet",
        "flowing", "fluent", "fond", "fresh", "friendly", "frisky", "frosty", "gallant", "genial", "gentle",
        "genuine", "giddy", "gilded", "glad", "gleaming", "glossy", "glowing", "golden", "graceful", "grand",
        "gusty", "handy", "happy", "hardy", "hearty", "heroic", "hidden", "honest", "hopeful", "humble", "hushed",
        "ideal", "indigo", "intrepid", "ivory", "jaunty", "jazzy", "jolly", "jovial", "joyful", "jubilant", "keen",
        "kind", "kindly", "leafy", "limber", "limpid", "lithe", "lively", "lofty", "loyal", "lucid", "lucky",
        "luminous", "lunar", "lush", "magic", "majestic", "marine", "mellow", "merry", "mighty", "mild", "mindful",
        "misty", "modest", "mossy", "mystic", "neat", "nifty", "nimble", "noble", "northern", "open", "pastel",
        "patient", "peaceful", "peppy", "perky", "placid", "pleasant", "plucky", "poised", "polar", "polished",
        "primal", "prime", "pristine", "proud", "pure", "quaint", "quick", "quiet", "radiant", "rapid", "rare",
        "ready", "regal", "restful", "roaming", "robust", "roomy", "rosy", "rousing", "royal", "rugged", "russet",
        "rustic", "sable", "salty", "sandy", "savvy", "scarlet", "scenic", "secret", "serene", "shady", "sharp",
        "shining", "shiny", "silent", "silken", "silver", "simple", "sincere", "sleek", "smooth", "snowy", "snug",
        "soaring", "soft", "solar", "solid", "sonic", "southern", "sparkling", "spicy", "spirited", "splendid",
        "spry", "stable", "starlit", "starry", "stately", "steady", "stellar", "still", "stoic", "stormy", "stout",
        "sturdy", "subtle", "summer", "sunlit", "sunny", "supple", "sure", "swift", "tender", "thrifty", "tidal",
        "tidy", "timeless", "tireless", "toasty", "tranquil", "tropical", "true", "trusty", "twilight", "unique",
        "upbeat", "urbane", "valiant", "vast", "velvet", "verdant", "vernal", "vibrant", "vigilant", "vital",
        "vivid", "wandering", "warm", "watchful", "western", "whimsical", "wild", "willing", "windy", "winged",
        "winter", "wintry", "wise", "witty", "wondrous", "woven", "young", "zealous", "zesty", "zippy",
    ];

    // 604 words: summits, stars, rivers, trees, flowers, birds and other animals, winds, stones, lands,
    // music, ships, old cities, lights, spices, tools and fruits.
    private static readonly string[] NounWords =
    [
        "abacus", "acacia", "achernar", "adagio", "agate", "albatross", "aldebaran", "alder", "alexandria", "algol",
        "alioth", "allegro", "alps", "altair", "amazon", "amethyst", "anchor", "andes", "andromeda", "anise",
        "annapurna", "antares", "antelope", "anthem", "anvil", "apricot", "aquila", "ararat", "archipelago",
        "arcturus", "aria", "aries", "armadillo", "arroyo", "aspen", "aster", "astrolabe", "athens", "atlas",
        "atoll", "auriga", "aurora", "avocet", "azalea", "babylon", "badger", "baker", "ballad", "bamboo", "banyan",
        "baobab", "barque", "basalt", "basil", "bayou", "beacon", "beam", "beaver", "beech", "begonia", "bellatrix",
        "beryl", "birch", "bison", "bittern", "blanc", "bluebell", "bluff", "bora", "breeze", "brig", "brook",
        "bunting", "butte", "buttercup", "byzantium", "cadence", "camellia", "canoe", "canon", "canopus", "canyon",
        "capella", "capybara", "cardamom", "cardinal", "caribou", "carina", "carol", "carthage", "cascade",
        "castor", "caucasus", "cavern", "cedar", "centauri", "cepheus", "cervin", "cetus", "chamois", "cheetah",
        "cherry", "chickadee", "chinchilla", "chinook", "chisel", "chord", "chorus", "cinnamon", "cirrus", "citron",
        "cliff", "clipper", "clove", "clover", "columba", "comet", "compass", "condor", "cook", "coriander",
        "corinth", "cormorant", "corona", "corvus", "cosmos", "cougar", "cove", "coyote", "crag", "crane", "creek",
        "crocus", "crux", "cuckoo", "cumin", "cumulus", "curlew", "cutter", "cygnus", "cypress", "dahlia", "daisy",
        "dale", "damson", "danube", "dawn", "daybreak", "delphi", "delta", "denali", "deneb", "diamond", "dipper",
        "dolomites", "dolphin", "dormouse", "dory", "dove", "draco", "duet", "dune", "dusk", "eagle", "easel",
        "ebro", "eclipse", "egret", "eiger", "elbe", "elbert", "elbrus", "elder", "electra", "elm", "ember",
        "encore", "equinox", "erebus", "ermine", "estuary", "etna", "everest", "falcon", "feldspar", "fennel",
        "fern", "ferry", "fig", "finch", "fir", "fjord", "flamingo", "flare", "flicker", "flint", "forge", "fornax",
        "fox", "foxglove", "freesia", "frigate", "frost", "fugue", "fuji", "galaxy", "gale", "galleon", "ganges",
        "gannet", "garnet", "garonne", "gazelle", "gemini", "gentian", "geyser", "ginger", "ginkgo", "glacier",
        "glade", "gleam", "glen", "glimmer", "glint", "glow", "goldfinch", "gorge", "goshawk", "granite", "grebe",
        "grove", "guava", "gust", "halo", "harbor", "hare", "harmony", "harrier", "hawk", "hawthorn", "heath",
        "heather", "hedgehog", "hekla", "helm", "hemlock", "heron", "hickory", "highland", "himalaya", "holly",
        "hood", "horizon", "hudson", "hummingbird", "hyacinth", "hydra", "ibex", "ibis", "impala", "indus", "iris",
        "island", "isle", "isthmus", "ithaca", "ivy", "izar", "jaguar", "jasmine", "jasper", "jay", "jordan",
        "jungfrau", "juniper", "kailash", "karakoram", "kayak", "keel", "kenya", "kestrel", "ketch", "kiln",
        "kingfisher", "kite", "kiwi", "knoll", "knossos", "koala", "lagoon", "lake", "lantern", "lapis", "lapwing",
        "larch", "lark", "lathe", "laurel", "lavender", "ledge", "lemon", "lemur", "lepus", "lhotse", "libra",
        "lilac", "lily", "lime", "linden", "linnet", "logan", "loire", "loom", "loon", "lotus", "lumen", "lupin",
        "lustre", "luxor", "lynx", "lyra", "lyric", "magnolia", "magpie", "maia", "makalu", "mango", "maple",
        "marble", "marigold", "marmot", "marsh", "marten", "martin", "mast", "matterhorn", "meadow", "meerkat",
        "mekong", "melody", "melon", "memphis", "merlin", "meru", "mesa", "meteor", "meuse", "mica", "mimosa",
        "minuet", "mira", "mist", "mistral", "mizar", "monsoon", "moor", "moose", "mosel", "motif", "mycenae",
        "myrtle", "nadir", "narcissus", "narwhal", "nebula", "nectarine", "niger", "nightingale", "nile", "nimbus",
        "nineveh", "nocturne", "nuthatch", "nutmeg", "oak", "oasis", "obsidian", "ocelot", "octave", "oder", "ohio",
        "olive", "olympia", "olympus", "onyx", "orca", "orchard", "orchid", "orinoco", "oriole", "orion", "osprey",
        "ossa", "otter", "overture", "owl", "palm", "palmyra", "pamir", "panda", "pangolin", "pansy", "papaya",
        "partridge", "pass", "pavo", "peach", "peacock", "peak", "pear", "pearl", "pegasus", "pelican", "pelion",
        "peninsula", "peony", "pepper", "perseus", "petra", "petrel", "petunia", "pheasant", "phoenix", "pilatus",
        "pine", "plateau", "plover", "plum", "polaris", "pollux", "poplar", "poppy", "potomac", "prairie",
        "prelude", "primrose", "prism", "procyon", "prow", "puffin", "pulsar", "puma", "pyrite", "pyxis", "quail",
        "quartz", "quasar", "quill", "quince", "radiance", "raft", "rainbow", "rainier", "rapids", "raven",
        "ravine", "ray", "redwood", "reef", "refrain", "regulus", "reprise", "rhapsody", "rhine", "rhone", "ridge",
        "rigel", "rigi", "robin", "robson", "rondo", "rosa", "rowan", "rudder", "saffron", "sage", "sail",
        "samarkand", "sandpiper", "sapphire", "savanna", "schooner", "seal", "seine", "sequoia", "serenade",
        "severn", "sextant", "shale", "shannon", "shasta", "shimmer", "shore", "shrike", "shuttle", "sierra",
        "sinai", "sirius", "sirocco", "skiff", "skylark", "slate", "sloop", "slope", "snowdrop", "solstice",
        "sonata", "sonnet", "sorrel", "spark", "sparrow", "sparta", "spica", "spindle", "spring", "spruce",
        "squall", "stag", "starling", "steppe", "stork", "strait", "stratus", "summit", "sundial", "sunflower",
        "sunrise", "sunset", "swallow", "swan", "sycamore", "tabor", "tagus", "taiga", "tamarind", "tarn",
        "tarragon", "taurus", "teide", "tempest", "tempo", "tern", "tetons", "thames", "thebes", "thistle",
        "thrush", "thunder", "thyme", "tiber", "tide", "tiger", "tigris", "tiller", "timbuktu", "topaz", "toubkal",
        "toucan", "trail", "tributary", "triglav", "trowel", "troy", "tulip", "tundra", "turquoise", "twinkle",
        "ural", "valley", "vanilla", "vega", "vela", "ventoux", "vesuvius", "vinson", "violet", "virgo", "vista",
        "volga", "wagtail", "wallaby", "waltz", "warbler", "watershed", "whitney", "willow", "wisteria", "wolf",
        "wombat", "woodpecker", "wren", "yak", "yarrow", "yawl", "yew", "yosemite", "yukon", "zagros", "zambezi",
        "zanzibar", "zenith", "zephyr", "zinnia", "zircon",
    ];
}
