import type { ComponentProps } from "react";
import {
  House,
  ArrowDown,
  ArrowUp,
  ArrowDownUp,
  CaseSensitive,
  CodeXml,
  Columns2,
  CopyMinus,
  Eye,
  FilePlus2,
  Files,
  FolderPlus,
  Hash,
  LocateFixed,
  Map as MapIcon,
  PanelLeft,
  Regex,
  Replace,
  Scan,
  SlidersHorizontal,
  WholeWord,
  ZoomIn,
  ZoomOut,
  FoldVertical,
  GitCompareArrows,
  List,
  ListTree,
  Rows2,
  Space,
  SquareArrowOutUpRight,
  UnfoldVertical,
  WrapText,
  Bot,
  Brain,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  MessageCircleQuestion,
  CircleAlert,
  CircleCheck,
  CircleDot,
  Clock3,
  Copy,
  CornerDownRight,
  CornerUpRight,
  Cpu,
  Ellipsis,
  FileDiff,
  Folder,
  GitBranch,
  Monitor,
  Moon,
  Sun,
  FolderOpen,
  FolderSearch,
  Gauge,
  History,
  Database,
  File,
  FileCode,
  FileImage,
  ImageOff,
  FileJson,
  FileTerminal,
  FileText,
  FileCog,
  GraduationCap,
  Palette,
  Plug,
  Puzzle,
  ScrollText,
  Server,
  Info,
  ListChecks,
  ListPlus,
  LibraryBig,
  MessageSquarePlus,
  Move,
  Minimize2,
  Minus,
  Plus,
  RotateCcw,
  Trash2,
  Maximize2,
  Archive,
  NotebookPen,
  Pencil,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  ShieldQuestion,
  Sparkles,
  Square,
  SquareTerminal,
  Terminal,
  ClipboardPaste,
  Eraser,
  TextSelect,
  Star,
  UserRound,
  X,
  type LucideIcon,
} from "lucide-react";

const icons = {
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  changes: GitCompareArrows,
  code: CodeXml,
  sidebar: PanelLeft,
  files: Files,
  newFile: FilePlus2,
  newFolder: FolderPlus,
  collapseAll: CopyMinus,
  star: Star,
  childSession: CornerDownRight,
  eye: Eye,
  goto: Hash,
  locate: LocateFixed,
  minimap: MapIcon,
  regex: Regex,
  caseSensitive: CaseSensitive,
  wholeWord: WholeWord,
  replace: Replace,
  filter: SlidersHorizontal,
  fit: Scan,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  columns: Columns2,
  rows: Rows2,
  fold: FoldVertical,
  unfold: UnfoldVertical,
  list: List,
  tree: ListTree,
  whitespace: Space,
  wrap: WrapText,
  openExternal: SquareArrowOutUpRight,
  archive: Archive,
  browse: LibraryBig,
  move: Move,
  newSession: MessageSquarePlus,
  open: FolderOpen,
  folderSearch: FolderSearch,
  minus: Minus,
  plus: Plus,
  reset: RotateCcw,
  restore: Minimize2,
  sort: ArrowDownUp,
  trash: Trash2,
  assistant: Bot,
  brain: Brain,
  check: Check,
  checked: CheckCheck,
  compact: Archive,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  ask: MessageCircleQuestion,
  close: X,
  reminder: Clock3,
  copy: Copy,
  error: CircleAlert,
  edit: Pencil,
  ellipsis: Ellipsis,
  expand: Maximize2,
  file: FileDiff,
  folder: Folder,
  home: House,
  history: History,
  issueOpen: CircleDot,
  issueClosed: CircleCheck,
  database: Database,
  fileGeneric: File,
  fileCode: FileCode,
  fileImage: FileImage,
  imageOff: ImageOff,
  fileJson: FileJson,
  fileTerminal: FileTerminal,
  fileText: FileText,
  config: FileCog,
  skill: GraduationCap,
  palette: Palette,
  provider: Plug,
  plugin: Puzzle,
  logs: ScrollText,
  server: Server,
  info: Info,
  model: Cpu,
  notes: NotebookPen,
  plan: ListChecks,
  queue: ListPlus,
  prompt: Sparkles,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  stop: Square,
  steer: CornerUpRight,
  settings: Settings,
  tool: SquareTerminal,
  terminal: Terminal,
  paste: ClipboardPaste,
  eraser: Eraser,
  selectAll: TextSelect,
  usage: Gauge,
  branch: GitBranch,
  themeDark: Moon,
  themeLight: Sun,
  themeSystem: Monitor,
  user: UserRound,
  question: ShieldQuestion,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function AppIcon({ name, ...props }: { name: IconName } & Omit<ComponentProps<LucideIcon>, "ref">) {
  const Icon = icons[name];
  return <Icon aria-hidden="true" focusable="false" strokeWidth={1.8} {...props} />;
}
