import type { ComponentProps } from "react";
import {
  ArrowDown,
  ArrowDownUp,
  Bot,
  Brain,
  Check,
  CheckCheck,
  ChevronDown,
  CircleAlert,
  Clock3,
  Copy,
  CornerUpRight,
  Cpu,
  Ellipsis,
  FileDiff,
  Folder,
  FolderOpen,
  Gauge,
  History,
  Info,
  ListChecks,
  ListPlus,
  LibraryBig,
  MessageSquarePlus,
  Move,
  Minimize2,
  Plus,
  RotateCcw,
  Trash2,
  Maximize2,
  Archive,
  NotebookPen,
  Pencil,
  RefreshCw,
  Search,
  Send,
  Settings,
  ShieldQuestion,
  Sparkles,
  Square,
  SquareTerminal,
  UserRound,
  X,
  type LucideIcon,
} from "lucide-react";

const icons = {
  arrowDown: ArrowDown,
  archive: Archive,
  browse: LibraryBig,
  move: Move,
  newSession: MessageSquarePlus,
  open: FolderOpen,
  plus: Plus,
  reset: RotateCcw,
  restore: Minimize2,
  sort: ArrowDownUp,
  trash: Trash2,
  assistant: Bot,
  brain: Brain,
  check: Check,
  checked: CheckCheck,
  compact: Archive,
  chevronDown: ChevronDown,
  close: X,
  reminder: Clock3,
  copy: Copy,
  error: CircleAlert,
  edit: Pencil,
  ellipsis: Ellipsis,
  expand: Maximize2,
  file: FileDiff,
  folder: Folder,
  history: History,
  info: Info,
  model: Cpu,
  notes: NotebookPen,
  plan: ListChecks,
  queue: ListPlus,
  prompt: Sparkles,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  stop: Square,
  steer: CornerUpRight,
  settings: Settings,
  tool: SquareTerminal,
  usage: Gauge,
  user: UserRound,
  question: ShieldQuestion,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function AppIcon({ name, ...props }: { name: IconName } & Omit<ComponentProps<LucideIcon>, "ref">) {
  const Icon = icons[name];
  return <Icon aria-hidden="true" focusable="false" strokeWidth={1.8} {...props} />;
}
